### ISSUE TITLE
Cannot find module `remark-lint`

### ISSUE THREAD

**Issue by pdxwolfy** [wooorm/linter-remark#1]
I get this error at the bottom of the screen in Atom 1.10.2 with linter-remark 2.1.0 and linter 1.11.16 installed when editing markdown files. I have tried uninstalling linter-remark and the reinstalling it, but it does not help.

**Comment by wooorm** [comment]
Hi @pdxwolfy, thanks for using remark.
Have you installed `remark-lint` somewhere?

**Comment by pdxwolfy** [comment]
Thanks, @wooorm I'm not sure how it got uninstalled, but reinstalling it seems to have fixed the issue.

**Comment by wooorm** [comment]
OK, glad it worked out!
