### ISSUE TITLE
Install plugins globally for use with linter-remark?

### ISSUE THREAD

**Issue by dionlarson** [wooorm/linter-remark#10]
Is there a way to install plugins globally for use with linter-remark? It seems that it does not pick up plugins installed with `npm install -g preset-name`.

**Comment by wooorm** [comment]
Nope! If you’re using remark, you should probably also add it to an `npm script` ([like so](https://github.com/wooorm/linter-remark/blob/21e831f2434cd6ca261e9a2121d7f5d8a2564d82/package.json#L41)).
It’s best to use as few global projects as possible (so other people could clone your project, run `npm install`, and be done with it).
