### ISSUE TITLE
Sharing configuration 

### ISSUE THREAD

**Issue by BrekiTomasson** [wooorm/linter-remark#11]
I run a documentation team at my place of work, and a lot of what we do is based around sharing a common set of Atom plug-ins.

I've been looking into implementing remark and retext into our workflow, so having the linter available for the developers would be very useful and save on the work required by myself in proofreading. 

Now; I've been trying to find a simple and/or straight forward method of sharing a configuration for the linter. The requirements would have to include :

- installing plug-ins from config file automatically
- be saved under the .atom directory rather than the documentation root.
- plug-ins should be saved on the local machine, not the (subversioned) document directory.

Is any of this possible, or do I need to build a package that does all the npm install work on each computer first?

**Comment by wooorm** [comment]
Hey @BrekiTomasson! 👋 

> I've been looking into implementing remark and retext into our workflow, so having the linter available for the developers would be very useful and save on the work required by myself in proofreading.

You can use [remark config](https://github.com/wooorm/remark/tree/master/packages/remark-cli#remark-cli---) files for that.

> installing plug-ins from config file automatically

Save remark and remark plugins in `package.json` and run `npm install` to download them.

> - Be saved under the .atom directory rather than the documentation root.
> - plug-ins should be saved on the local machine, not the (subversioned) document directory.

Why? Just use npm for plugins, store a `.remarkrc` somewhere in the project root, and let people `npm install` to load everything.

Benefit: you can run `remark` (the CLI) in a CI, like Travis. Then, people *could* use `linter-remark` if they’re using Atom, but that’s optional.
